[project]
name = "building-with-rag"
version = "0.1.0"
authors = [
    { name = "tayyabk121", email = "tayyabkhanbhopal@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.142.2",
    "pydantic-settings>=2.15.0",
    "pymongo>=4.18.2",
    "uvicorn[standard]>=0.54.0",
]

[build-system]
requires = ["uv_build>=0.11.29,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.1.1",
    "ruff>=0.16.10",
]
